#!/usr/bin/env sh

set -eu

: "${DEPLOY_PATH:?DEPLOY_PATH is required}"
: "${DOMAIN_NAME:?DOMAIN_NAME is required}"
: "${MYSQL_ROOT_PASSWORD:?MYSQL_ROOT_PASSWORD is required}"
: "${MYSQL_DATABASE:?MYSQL_DATABASE is required}"
: "${MYSQL_USER:?MYSQL_USER is required}"
: "${MYSQL_PASSWORD:?MYSQL_PASSWORD is required}"
: "${JWT_SECRET:?JWT_SECRET is required}"

mkdir -p "$DEPLOY_PATH" "$DEPLOY_PATH/nginx" "$DEPLOY_PATH/certs" "$DEPLOY_PATH/www"

cat > "$DEPLOY_PATH/.env" <<EOF
DOMAIN_NAME=$DOMAIN_NAME

MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
MYSQL_DATABASE=$MYSQL_DATABASE
MYSQL_USER=$MYSQL_USER
MYSQL_PASSWORD=$MYSQL_PASSWORD

JWT_SECRET=$JWT_SECRET
AUTO_SEED_ADMIN=${AUTO_SEED_ADMIN:-false}
ENABLE_INVOICE_SCHEDULER=${ENABLE_INVOICE_SCHEDULER:-true}
ENABLE_TRIAL_SCHEDULER=${ENABLE_TRIAL_SCHEDULER:-true}

BACKEND_IMAGE=${BACKEND_IMAGE:-ghcr.io/adipras/tirta-saas-backend:latest}
FRONTEND_IMAGE=${FRONTEND_IMAGE:-ghcr.io/adipras/tirta-saas-frontend:latest}

MYSQL_IMAGE=${MYSQL_IMAGE:-mysql:8.0}
NGINX_IMAGE=${NGINX_IMAGE:-nginx:1.27-alpine}
NETDATA_IMAGE=${NETDATA_IMAGE:-netdata/netdata:stable}
NETDATA_HOSTNAME=${NETDATA_HOSTNAME:-tirta-vps}
EOF
